//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviews.AdminUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviePoster
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public byte[] PosterImage { get; set; }
        public string MimeType { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
